use crate::config::Config;
use crate::types::MediaType;
use log::debug;
use objc2_app_kit::NSPasteboard;
use objc2_foundation::NSString;

const CONCEALED_TYPE: &str = "org.nspasteboard.ConcealedType";
const TRANSIENT_TYPE: &str = "org.nspasteboard.TransientType";
const AUTO_GENERATED_TYPE: &str = "org.nspasteboard.AutoGeneratedType";
const ONEPASSWORD_TYPE: &str = "com.agilebits.onepassword";
const PASSWORD_PBOARD_TYPE: &str = "PasswordPboardType";
const SOURCE_TYPE: &str = "org.nspasteboard.source";

const PBRING_BUNDLE_ID: &str = "com.pbring.daemon";

// Known pasteboard type constants
const NS_STRING_PBOARD_TYPE: &str = "public.utf8-plain-text";
const NS_TIFF_PBOARD_TYPE: &str = "public.tiff";
const NS_PNG_PBOARD_TYPE: &str = "public.png";
const NS_FILE_URL_TYPE: &str = "public.file-url";

pub struct PasteboardContent {
    pub data: Vec<u8>,
    pub media_type: MediaType,
    pub preview: String,
    pub source_app: Option<String>,
}

pub struct PasteboardReader {
    last_change_count: isize,
    preview_max_chars: usize,
    extra_ignored_types: Vec<String>,
    ignored_apps: Vec<String>,
}

impl PasteboardReader {
    pub fn new(config: &Config) -> Self {
        Self {
            last_change_count: 0,
            preview_max_chars: config.preview_max_chars,
            extra_ignored_types: config.extra_ignored_types.clone(),
            ignored_apps: config.ignored_apps.clone(),
        }
    }

    pub fn init_change_count(&mut self) {
        let pb = NSPasteboard::generalPasteboard();
        self.last_change_count = pb.changeCount();
    }

    pub fn poll(&mut self) -> Option<PasteboardContent> {
        let pb = NSPasteboard::generalPasteboard();
        let current_count = pb.changeCount();

        if current_count == self.last_change_count {
            return None;
        }
        self.last_change_count = current_count;

        let types = self.get_type_strings(&pb);
        debug!("Pasteboard types: {:?}", types);

        // Check security markers
        if self.should_ignore(&types) {
            debug!("Ignoring pasteboard content due to security markers");
            return None;
        }

        // Check source (loop prevention)
        if let Some(source) = self.get_source_string(&pb) {
            if source == PBRING_BUNDLE_ID {
                debug!("Ignoring own pasteboard content");
                return None;
            }
            if self.ignored_apps.contains(&source) {
                debug!("Ignoring content from ignored app: {}", source);
                return None;
            }
        }

        // Read content by priority: Text > Image > File > Other
        self.read_content(&pb, &types)
    }

    fn get_type_strings(&self, pb: &NSPasteboard) -> Vec<String> {
        let mut result = Vec::new();
        if let Some(types) = pb.types() {
            let count = types.len();
            for i in 0..count {
                let t = types.objectAtIndex(i);
                result.push(t.to_string());
            }
        }
        result
    }

    fn get_source_string(&self, pb: &NSPasteboard) -> Option<String> {
        let source_type = NSString::from_str(SOURCE_TYPE);
        let data = pb.stringForType(&source_type);
        data.map(|s| s.to_string())
    }

    fn should_ignore(&self, types: &[String]) -> bool {
        let ignored = [
            CONCEALED_TYPE,
            TRANSIENT_TYPE,
            AUTO_GENERATED_TYPE,
            ONEPASSWORD_TYPE,
            PASSWORD_PBOARD_TYPE,
        ];

        for t in types {
            if ignored.contains(&t.as_str()) {
                return true;
            }
            if self.extra_ignored_types.iter().any(|e| e == t) {
                return true;
            }
        }
        false
    }

    fn read_content(&self, pb: &NSPasteboard, types: &[String]) -> Option<PasteboardContent> {
        let source_app = self.get_source_string(pb);

        // Text
        if types.iter().any(|t| t == NS_STRING_PBOARD_TYPE) {
            let pb_type = NSString::from_str(NS_STRING_PBOARD_TYPE);
            if let Some(s) = pb.stringForType(&pb_type) {
                let text = s.to_string();
                if text.is_empty() {
                    return None;
                }
                let preview = generate_text_preview(&text, self.preview_max_chars);
                return Some(PasteboardContent {
                    data: text.into_bytes(),
                    media_type: MediaType::Text,
                    preview,
                    source_app,
                });
            }
        }

        // Image (PNG preferred, then TIFF)
        for (img_type, label) in [
            (NS_PNG_PBOARD_TYPE, "PNG"),
            (NS_TIFF_PBOARD_TYPE, "TIFF"),
        ] {
            if types.iter().any(|t| t == img_type) {
                let pb_type = NSString::from_str(img_type);
                if let Some(data) = pb.dataForType(&pb_type) {
                    let bytes = unsafe { data.as_bytes_unchecked() }.to_vec();
                    if bytes.is_empty() {
                        continue;
                    }
                    let preview = format!("[image {label} {} bytes]", bytes.len());
                    return Some(PasteboardContent {
                        data: bytes,
                        media_type: MediaType::Image,
                        preview,
                        source_app,
                    });
                }
            }
        }

        // File URL
        if types.iter().any(|t| t == NS_FILE_URL_TYPE) {
            let pb_type = NSString::from_str(NS_FILE_URL_TYPE);
            if let Some(s) = pb.stringForType(&pb_type) {
                let url = s.to_string();
                if !url.is_empty() {
                    let path = url.strip_prefix("file://").unwrap_or(&url);
                    let preview = format!("[file {}]", path);
                    return Some(PasteboardContent {
                        data: url.into_bytes(),
                        media_type: MediaType::File,
                        preview,
                        source_app,
                    });
                }
            }
        }

        None
    }
}

pub fn generate_text_preview(text: &str, max_chars: usize) -> String {
    let mut preview = String::new();
    let mut char_count = 0;
    for c in text.chars() {
        if char_count >= max_chars {
            break;
        }
        match c {
            '\n' => preview.push_str("\\n"),
            '\r' => preview.push_str("\\r"),
            '\t' => preview.push_str("\\t"),
            _ => preview.push(c),
        }
        char_count += 1;
    }
    preview
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_should_ignore_concealed() {
        let reader = PasteboardReader {
            last_change_count: 0,
            preview_max_chars: 100,
            extra_ignored_types: vec![],
            ignored_apps: vec![],
        };
        let types = vec![
            "public.utf8-plain-text".to_string(),
            "org.nspasteboard.ConcealedType".to_string(),
        ];
        assert!(reader.should_ignore(&types));
    }

    #[test]
    fn test_should_ignore_transient() {
        let reader = PasteboardReader {
            last_change_count: 0,
            preview_max_chars: 100,
            extra_ignored_types: vec![],
            ignored_apps: vec![],
        };
        let types = vec!["org.nspasteboard.TransientType".to_string()];
        assert!(reader.should_ignore(&types));
    }

    #[test]
    fn test_should_ignore_onepassword() {
        let reader = PasteboardReader {
            last_change_count: 0,
            preview_max_chars: 100,
            extra_ignored_types: vec![],
            ignored_apps: vec![],
        };
        let types = vec!["com.agilebits.onepassword".to_string()];
        assert!(reader.should_ignore(&types));
    }

    #[test]
    fn test_should_not_ignore_normal() {
        let reader = PasteboardReader {
            last_change_count: 0,
            preview_max_chars: 100,
            extra_ignored_types: vec![],
            ignored_apps: vec![],
        };
        let types = vec!["public.utf8-plain-text".to_string()];
        assert!(!reader.should_ignore(&types));
    }

    #[test]
    fn test_should_ignore_extra() {
        let reader = PasteboardReader {
            last_change_count: 0,
            preview_max_chars: 100,
            extra_ignored_types: vec!["com.custom.secret".to_string()],
            ignored_apps: vec![],
        };
        let types = vec!["com.custom.secret".to_string()];
        assert!(reader.should_ignore(&types));
    }

    #[test]
    fn test_generate_text_preview() {
        assert_eq!(generate_text_preview("hello", 100), "hello");
        assert_eq!(generate_text_preview("hello\nworld", 100), "hello\\nworld");
        assert_eq!(generate_text_preview("abcdef", 3), "abc");
    }

    #[test]
    fn test_generate_text_preview_unicode() {
        assert_eq!(generate_text_preview("こんにちは", 3), "こんに");
    }

    #[test]
    fn test_should_ignore_password_pboard_type() {
        let reader = PasteboardReader {
            last_change_count: 0,
            preview_max_chars: 100,
            extra_ignored_types: vec![],
            ignored_apps: vec![],
        };
        let types = vec!["PasswordPboardType".to_string()];
        assert!(reader.should_ignore(&types));
    }

    #[test]
    fn test_should_ignore_auto_generated() {
        let reader = PasteboardReader {
            last_change_count: 0,
            preview_max_chars: 100,
            extra_ignored_types: vec![],
            ignored_apps: vec![],
        };
        let types = vec!["org.nspasteboard.AutoGeneratedType".to_string()];
        assert!(reader.should_ignore(&types));
    }
}
